# Generated by Django 4.2.1 on 2023-05-29 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_tracker', '0005_remove_movie_is_favorite_favoritemovie'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='FavoriteMovie',
        ),
    ]
